import os, sys, time
WINDOWS=os.name=='nt'
if WINDOWS:
    import msvcrt
else:
    import termios, tty, select
def clear_keystrokes():
    if WINDOWS:
        while msvcrt.kbhit():
            msvcrt.getch()
    else:
        while select.select([sys.stdin], [], [], 0)[0]:
            sys.stdin.read(1)

def typing(text, delay=0.01):
    sys.stdout.write("\033[?25l")
    sys.stdout.flush()

    if not WINDOWS:
        old_settings = termios.tcgetattr(sys.stdin)
        tty.setcbreak(sys.stdin.fileno())

    try:
        for c in text:
            clear_keystrokes()
            sys.stdout.write(c)
            sys.stdout.flush()
            time.sleep(delay)
    finally:
        if not WINDOWS:
            termios.tcsetattr(sys.stdin, termios.TCSADRAIN, old_settings)
        sys.stdout.write("\033[?25h")
        sys.stdout.flush()

def delete():
    os.system('cls' if os.name == 'nt' else 'clear')
sekilas="{"
sekilas1="}"
RED = '\033[31m'
YELLOW = '\033[33m'
CYAN = '\033[36m'
GRAY= '\033[90m'
GREEN = '\033[32m'
BLUE = "\033[0;34m"
MAGENTA = '\033[35m'
DARK_GRAY = "\033[1;30m"
BRIGHT_RED = '\033[91m'
BRIGHT_BLUE = '\033[94m'
BRIGHT_YELLOW = '\033[93m'
BRIGHT_GREEN = '\033[92m'
BG_BRIGHT_WHITE = '\033[107m'
BRIGHT_WHITE = '\033[97m'
BG_RED = '\033[41m'
BG_GREEN = '\033[42m'
BG_BLACK = '\033[40m'
BG_CYAN = '\033[46m'
ITALIC = '\x1B[3m'
RESET = '\033[0m'
import os


def main():
	delete()
	typing(f"Halo {name}!")
	print()
	typing("Saya akan membantu mu dalam mempelajari python!")
	print()
	typing("silahkan pilih salah satu yang ada di bawah ini dan saya akan menjelaskannya kepada mu:")
	print()
	print("1. tipe data")
	print("2. print dan input")
	print("3. concatenation")
	print("4. conditional statement(if, elif, dan else)")
	print("5. loop(for dan while)")
	print("6. def(define)")
	print("7. list")
	print("8. import data")
	print("9. try... except...finally")
	print("10. global data")
	i=int(input(">"))
	if i==1:
		data()
	elif i==2:
		inputs()
	elif i==3:
		concat()
	elif i==4:
		cond()
	elif i==5:
		loop()
	elif i==6:
		defs()
	elif i==7:
		listing()
	elif i==8:
		imports()
	elif i==9:
		tryex()
	elif i==10:
		globals()
	else:
		main()

def data():
	delete()
	typing("jadi, ada beberapa macam tipe data, yaitu")
	print()
	typing(f"1. {BLUE}\x1B[3mint\x1B[3m{RESET}(integer)")
	print()
	typing(f"   {BLUE}\x1B[3mint\x1B[3m{RESET} merupakan sebuah data dengan bilangan bulat")
	print()
	typing(f"   contohnya: x{RED}={YELLOW}6")
	print()
	typing(f"              {BLUE}\x1B[3mprint\x1B[3m{RESET}(x)")
	print()
	typing("   outputnya adalah: 6")
	print()
	input(f"{DARK_GRAY}klik enter untuk melanjutkan.{RESET}")
	print()
	typing(f"2. {BLUE}\x1B[3mstr\x1B[3m{RESET}(string)")
	print()
	typing(f"   {BLUE}\x1B[3mstr\x1B[3m{RESET} merupakan sebuah tipe data berisikan kata atau kalimat")
	print()
	typing(f"   {BLUE}\x1B[3mstr\x1B[3m{RESET} biasanya di deklarasikan menggunakan ' '")
	print()
	typing(f"   contohnya: x{RED}={RESET}({BRIGHT_BLUE}'{BRIGHT_GREEN}halo{BRIGHT_BLUE}'{RESET})")
	print()
	typing(f"              {BLUE}\x1B[3mprint\x1B[3m{RESET}(x)")
	print()
	typing("   outputnya adalah: halo")
	print()
	input(f"{DARK_GRAY}klik enter untuk melanjutkan.{RESET}")
	print()
	typing(f"3. {BLUE}\x1B[3mcomplex\x1B[3m{RESET}")
	print()
	typing(f"   tipe data {BLUE}\x1B[3mcomplex\x1B[3m{RESET} bisa menyimpan data angka dan kata")
	print()
	typing(f"   contohnya: x{RED}={YELLOW}4{RED}+{YELLOW}3{RESET}j")
	print()
	typing(f"              {BLUE}\x1B[3mprint\x1B[3m{RESET}(x)")
	print()
	typing("   outputnya adalah: 4+3j")
	print()
	input(f"{DARK_GRAY}klik enter untuk melanjutkan.{RESET}")
	print()
	typing(f"4. {BLUE}\x1B[3mbool\x1B[3m{RESET}(boolean)")
	print()
	typing(f"   tipe data {BLUE}\x1B[3mbool\x1B[3m{RESET} seting digunakan untuk menyatakan {RED}True{RESET} atau {RED}False{RESET}")
	print()
	typing(f"   contohnya:{BLUE}\x1B[3mprint\x1B[3m{RESET}({BRIGHT_BLUE}'{BRIGHT_GREEN}10>9{BRIGHT_BLUE}'{RESET})")
	print()
	typing(f"             {BLUE}\x1B[3mprint\x1B[3m{RESET}({BRIGHT_BLUE}'{BRIGHT_GREEN}10<9{BRIGHT_BLUE}'{RESET})")
	print()
	typing("   outputnya adalah: True")
	print()
	typing("                     False")
	print()
	input(f"{DARK_GRAY}klik enter untuk melanjutkan.{RESET}")
	print()
	typing(f"5. {BLUE}\x1B[3mlist\x1B[3m{RESET}")
	print()
	typing(f"   {BLUE}\x1B[3mlist\x1B[3m{RESET} adalah jenis data yang berisi beberapa data sekaligus")
	print()
	typing(f"   {BLUE}\x1B[3mlist\x1B[3m{RESET} ditandai dengan tanda =[]")
	print()
	typing(f"   isi dari {BLUE}\x1B[3mlist\x1B[3m{RESET} diawali dengan [{YELLOW}0{RESET}]")
	print()
	typing(f"   data dalam {BLUE}\x1B[3mlist\x1B[3m{RESET} bisa di tambah dan kurangi")
	print()
	typing(f"   contohnya: x{RED}={RESET}[{YELLOW}13{RESET},{YELLOW}15{RESET},{YELLOW}17{RESET},{YELLOW}19{RESET},{YELLOW}21{RESET}{RESET}]")
	print()
	typing(f"              y{RED}={RESET}[{BRIGHT_BLUE}'{BRIGHT_GREEN}Yang{BRIGHT_BLUE}'{RESET}, {BRIGHT_BLUE}'{BRIGHT_GREEN}{name}{BRIGHT_BLUE}'{RESET}, {BRIGHT_BLUE}'{BRIGHT_GREEN}Baik{BRIGHT_BLUE}'{RESET}, {BRIGHT_BLUE}'{BRIGHT_GREEN}Sangat{BRIGHT_BLUE}'{RESET}]")
	print()
	typing(f"              {BLUE}\x1B[3mprint\x1B[3m{RESET}(x)")
	print()
	typing(f"              {BLUE}\x1B[3mprint\x1B[3m{RESET}(y[{YELLOW}1{RESET}])")
	print()
	typing(f"              {BLUE}\x1B[3mprint\x1B[3m{RESET}(y[{YELLOW}1{RESET}],y[{YELLOW}0{RESET}],y[{YELLOW}3{RESET}],y[{YELLOW}4{RESET}])")
	print()
	typing("    outputnya adalah: [13,15,17,19,21]")
	print()
	typing(f"                      {name}")
	print()
	typing(f"                      {name} Yang Sangat Baik")
	print()
	input(f"{DARK_GRAY}klik enter untuk melanjutkan.{RESET}")
	print()
	typing(f"6. {BLUE}\x1B[3mtuple\x1B[3m{RESET}")
	print()
	typing(f"   {BLUE}\x1B[3mtuple\x1B[3m{RESET} hampir sama dengan {BLUE}\x1B[3mlist\x1B[3m{RESET}. Perbedaannya ada di ()")
	print()
	typing(f"   {BLUE}\x1B[3mtuple\x1B[3m{RESET} menggunakan tanda (). Sedangkan list menggunakan tanda []")
	print()
	typing(f"   data dalam {BLUE}\x1B[3mtuple\x1B[3m{RESET} juga tidak bisa di utak atik")
	print()
	typing(f"   contohnya: y{RED}={RESET}({BRIGHT_BLUE}'{BRIGHT_GREEN}Kamu{BRIGHT_BLUE}'{BRIGHT_GREEN}, {BRIGHT_BLUE}'{BRIGHT_GREEN}Aku{BRIGHT_BLUE}'{BRIGHT_GREEN}, {BRIGHT_BLUE}'{BRIGHT_GREEN}Cinta{BRIGHT_BLUE}'{RESET})")
	print()
	typing(f"              {BLUE}\x1B[3mprint\x1B[3m{RESET}(y[{YELLOW}1{RESET}])")
	print()
	typing(f"              {BLUE}\x1B[3mprint\x1B[3m{RESET}(y[{YELLOW}1{RESET}],y[{YELLOW}2{RESET}],y[{YELLOW}0{RESET}])")
	print()
	typing("    outputnya adalah: Aku")
	print()
	typing("                      Aku Cinta Kamu ")
	print()
	input(f"{DARK_GRAY}klik enter untuk melanjutkan.{RESET}")
	print()
	typing(f"7. {BLUE}\x1B[3mdict\x1B[3m{RESET}(dictionary)")
	print()
	typing(f"   {BLUE}\x1B[3mdict\x1B[3m{RESET} adalah kumpulan kata kunci dan isi/nilainya")
	print()
	typing(f"   {BLUE}\x1B[3mdict\x1B[3m{RESET} menggunakan tanda {sekilas}{sekilas1}")
	print()
	typing(f"   contohnya: x={sekilas}'{BRIGHT_BLUE}aku'{RESET}:{BRIGHT_BLUE}'{BRIGHT_GREEN}justin{BRIGHT_BLUE}'{RESET}, {BRIGHT_BLUE}'kamu'{RESET}:{BRIGHT_BLUE}'{BRIGHT_GREEN}{name}{BRIGHT_BLUE}'{RESET}, {BRIGHT_BLUE}'x'{RESET}:{BRIGHT_BLUE}'{BRIGHT_GREEN}dan{BRIGHT_BLUE}'{RESET}{sekilas1} ")
	print()
	typing(f"              {BLUE}\x1B[3mprint\x1B[3m{RESET}(x)")
	print()
	typing(f"              {BLUE}\x1B[3mprint\x1B[3m{RESET}(c[{BRIGHT_BLUE}'{BRIGHT_GREEN}aku{BRIGHT_BLUE}'{RESET}],c[{BRIGHT_BLUE}'{BRIGHT_GREEN}x{BRIGHT_BLUE}'{RESET}],c[{BRIGHT_BLUE}'{BRIGHT_GREEN}kamu{BRIGHT_BLUE}'{RESET}])")
	print()
	typing(f"   outputnya adalah: {{'aku':'justin', 'kamu':'{name}', 'x':'dan'}}")
	print()
	typing(f"                     justin dan {name}")
	print()
	input(f"{DARK_GRAY}klik enter untuk kembali.{RESET}")
	main()

def inputs():
	delete()
	typing(f"untuk {BLUE}\x1B[3mprint\x1B[3m{RESET} dan {BLUE}\x1B[3minput\x1B[3m{RESET} pasti kamu sudah tau")
	print()
	typing(f"tapi ada beberapa cara pengetikan {BLUE}\x1B[3mprint\x1B[3m{RESET} dengan {BLUE}\x1B[3minput\x1B[3m{RESET} yang mungkin kamu tidak tau")
	print()
	input(f"{DARK_GRAY}klik enter untuk melanjutkan.{RESET}")
	print()
	typing(f"untuk {BLUE}\x1B[3mprint\x1B[3m{RESET}, ada yang namanya f-string")
	print()
	typing(f"format f-string sangat berguna jika kamu ingin {BLUE}\x1B[3mprint\x1B[3m{RESET} kalimat dengan sebuah variable yang sudah kamu bikin")
	print()
	typing(f"contohnya: x{RED}={YELLOW}16{RESET}")
	print()
	typing(f"           {BLUE}\x1B[3mprint\x1B[3m{RESET}({MAGENTA}\x1B[3mf\x1B[3m{BRIGHT_BLUE}'{BRIGHT_GREEN}saya berumur {RESET}{sekilas}x{sekilas1}{BRIGHT_GREEN} tahun{BRIGHT_BLUE}'{RESET})")
	print()
	typing("outputnya adalah: saya berumur 16 tahun")
	print()
	print()
	typing(f"dan dengan mengetikkan {BLUE}\x1B[3mprint\x1B[3m{RESET}()")
	print()
	typing("itu bisa menjadi spasi dalam programmu")
	print()
	input(f"{DARK_GRAY}klik enter untuk melanjutkan.{RESET}")
	print()
	typing(f"untuk {BLUE}\x1B[3minput\x1B[3m{RESET}, ada beberapa cara unik yang bisa dipakai yaitu:")
	print()
	typing(f"1. untuk jeda sampai kamu {BLUE}\x1B[3minput\x1B[3m{RESET} sesuatu")
	print()
	typing(f"   untuk membuat jeda, kamu hanya perlu ketik: {BLUE}\x1B[3minput\x1B[3m{RESET}(' ')")
	print()
	typing("   dengan begitu, program yang kamu bikin akan berhenti dan menunggu hingga kamu memberi sebuah imputan")
	print()
	print()
	typing(f"2. cara simpel untuk {BLUE}\x1B[3minput\x1B[3m{RESET} {BLUE}\x1B[3mint\x1B[3m{RESET}")
	print()
	typing("   jika ingin membuat seperti pilihan dari 1 samapai 5, cukup membuat:")
	print()
	print()
	typing(f"   pilihan{RED}={BLUE}\x1B[3mint\x1B[3m{RESET}({BLUE}\x1B[3minput\x1B[3m{RESET}('pilih angka 1 sampai 5: '))")
	print()
	typing(f"   {BRIGHT_RED}atau{RESET}")
	print()
	typing(f"   {BLUE}\x1B[3mprint\x1B[3m{RESET}({BRIGHT_BLUE}'{BRIGHT_GREEN}pilih angka 1 sampai 5{BRIGHT_BLUE}'{RESET})")
	print()
	typing(f"   pilihan{RED}={BLUE}\x1B[3mint\x1B[3m{RESET}({BLUE}\x1B[3minput\x1B[3m{RESET}({BRIGHT_BLUE}'{BRIGHT_GREEN}> {BRIGHT_BLUE}'{RESET}))")
	print()
	input(f"{DARK_GRAY}klik enter untuk kembali.{RESET}")
	main()

def concat():
	delete()
	typing("concatenation adalah penggabungan 2 kata")
	print()
	typing("ada beberapa cara concatenation yang bisa dilakukan, yaitu:")
	print()
	input(f"{DARK_GRAY}klik enter untuk melanjutkan.{RESET}")
	print()
	typing(f"1.menggunakan '{RED}+{RESET}'")
	print()
	typing(f"  concatenation menggunakan '{RED}+{RESET}' akan menambahkan dua string")
	print()
	typing(f"  contohnya: a{RED}={BRIGHT_BLUE}'{BRIGHT_GREEN}Hai{BRIGHT_BLUE}'{RESET}")
	print()
	typing(f"             b{RED}={BRIGHT_BLUE}'{BRIGHT_GREEN}{name}{BRIGHT_BLUE}'{RESET}")
	print()
	typing(f"             {BLUE}\x1B[3mprint\x1B[3m{RESET}(a{RED}+{RESET}b)")
	print()
	typing(f"  outputnya adalah: Hai{name}")
	print()
	input(f"{DARK_GRAY}klik enter untuk melanjutkan.{RESET}")
	print()
	typing(f"2. menggunakan '{GRAY},{RESET}'")
	print()
	typing(f"concatenation menggunakan '{GRAY},{RESET}' akan menambahkan dua string yang terpisahkan oleh spasi")
	print()
	typing(f"  contohnya: a{RED}={BRIGHT_BLUE}'{BRIGHT_GREEN}Hai{BRIGHT_BLUE}'{RESET}")
	print()
	typing(f"             b{RED}={BRIGHT_BLUE}'{BRIGHT_GREEN}{name}{BRIGHT_BLUE}'{RESET}")
	print()
	typing(f"             {BLUE}\x1B[3mprint\x1B[3m{RESET}(a{GRAY},{RESET}b)")
	print()
	typing(f"  outputnya adalah: Hai {name}")
	print()
	input(f"{DARK_GRAY}klik enter untuk melanjutkan.{RESET}")
	print()
	typing(f"3. menggunakan ' {RED}+{RESET}{BRIGHT_BLUE}' '{RED}+{RESET} '")
	print()
	typing(f"   concatenation menggunakan ' {RED}+{RESET}{BRIGHT_BLUE}' '{RED}+{RESET} ' akam menghasilkan hasil yang sama dengan menggunakan ','")
	print()
	typing(f"  contohnya: a{RED}={BRIGHT_BLUE}'{BRIGHT_GREEN}Hai{BRIGHT_BLUE}'{RESET}")
	print()
	typing(f"             b{RED}={BRIGHT_BLUE}'{BRIGHT_GREEN}{name}{BRIGHT_BLUE}'{RESET}")
	print()
	typing(f"             {BLUE}\x1B[3mprint\x1B[3m{RESET}(a{RED}+{BRIGHT_BLUE}' '{RED}+{RESET}b)")
	print()
	typing(f"  outputnya adalah: Hai {name}")
	print()
	input(f"{DARK_GRAY}klik enter untuk kembali.{RESET}")
	main()

def cond():
	delete()
	typing("conditional statement adalah fungsi yang digunakan untuk membandingkan sesuatu")
	print()
	typing("ada beberapa conditional statement, yaitu:")
	print()
	input(f"{DARK_GRAY}klik enter untuk melanjutkan.{RESET}")
	print()
	typing(f"1. {MAGENTA}if{RESET}")
	print()
	typing(f"   {MAGENTA}i{RESET}f merupakan conditional statement yang menentukan jika suatu variabel cocok dengn nilai yang ditentukan")
	print()
	input(f"{DARK_GRAY}klik enter untuk melanjutkan.{RESET}")
	print()
	typing(f"2. {MAGENTA}elif{RESET}")
	print()
	typing(f"   {MAGENTA}elif{RESET} merupakan conditional statement yang menentukan nilai selain nilai yang ditentukan di fungsi {MAGENTA}if{RESET}")
	print()
	input(f"{DARK_GRAY}klik enter untuk melanjutkan.{RESET}")
	print()
	typing(f"3. {MAGENTA}else{RESET}")
	print()
	typing(f"   {MAGENTA}else{RESET} merupakan conditional statement yang mentukan nilai selain nilai di fungsi {MAGENTA}if{RESET} dan {MAGENTA}elif{RESET}")
	print()
	input(f"{DARK_GRAY}klik enter untuk melanjutkan.{RESET}")
	print()
	typing(f"4. {RED}and{RESET}")
	print()
	typing(f"   {RED}and{RESET} berfungsi untuk menjalankan program jika kedua persyaratan benar")
	print()
	input(f"{DARK_GRAY}klik enter untuk melanjutkan.{RESET}")
	print()
	typing(f"5. {RED}or{RESET}")
	print()
	typing(f"   {RED}or{RESET} berfungsi untuk menjalankan program jika salah satu persyaratan benar")
	print()
	input(f"{DARK_GRAY}klik enter untuk melanjutkan.{RESET}")
	print()
	typing(f"6.{RED}not{RESET}")
	print()
	typing(f"   {RED}not{RESET} befungsi untuk membalikkan fungsi {RED}or{RESET} dan {RED}and{RESET}")
	print()
	typing(f"   jadi fungsi {RED}or{RESET} harus dua duanya benar")
	print()
	typing(f"   dan fungsi {RED}and{RESET} harus salah satunya benar")
	print()
	input(f"{DARK_GRAY}klik enter untuk kembali.{RESET}")
	main()

def loop():
	delete()
	typing("loop merupakan fungsi untuk mengulangi suatu program berkali-kali sebanyak batas yang ditentukan")
	print()
	typing("loop ada 2 macam, yaitu for dan while.")
	print()
	input(f"{DARK_GRAY}klik enter untuk melanjutkan.{RESET}")
	typing(f"1.{MAGENTA}for{RESET}")
	print()
	typing(f"  {MAGENTA}for{RESET} adalah fungsi looping yang berguna untuk mengulangi suatu program dengan batasan berupa {BLUE}\x1B[3mrange\x1B[3m{RESET}.")
	print()
	typing(f"  contohnya: angka{RED}={YELLOW}0{RESET}")
	print()
	typing(f"             {MAGENTA}for{RESET} angka {RED}in {BLUE}range{RESET}({YELLOW}5{RESET}):")
	print()
	typing(f"                 {BLUE}print{RESET}(angka)")
	print()
	typing("  outputnya adalah: 0")
	print()
	typing("                    1")
	print()
	typing("                    2")
	print()
	typing("                    3")
	print()
	typing("                    4")
	print()
	typing(f"  outputnya akan berjalan sebanyak {YELLOW}5{RESET} kali")
	print()
	input(f"{DARK_GRAY}klik enter untuk melanjutkan.{RESET}")
	print()
	print()
	typing(f"2.{MAGENTA}while{RESET}")
	print()
	typing(f"  {MAGENTA}while{RESET} adalah fungsi untuk mengulangi suatu program dengan batasan berupa '{RED}>{RESET}','{RED}<{RESET}','{RED}True{RESET}'','{RED}False{RESET}'")
	print()
	typing(f"  perulangan {MAGENTA}while{RESET} harus disertakan kode untuk menambah angka agar fungsi {MAGENTA}while{RESET} nya tidak berjalan tanpa henti.")
	print()
	typing(f"  contohnya: angka{RED}={YELLOW}0{RESET}")
	print()
	typing(f"             {MAGENTA}while{RESET} angka {RED}<{YELLOW}5{RESET}:")
	print()
	typing(f"                 {BLUE}print{RESET}(angka)")
	print()
	typing(f"                 angka{RED}+={YELLOW}1{RESET} {GRAY}#agar angkanya bertambah 1 setiap kali diulang.{RESET}")
	print()
	typing("  outputnya adalah: 0")
	print()
	typing("                    1")
	print()
	typing("                    2")
	print()
	typing("                    3")
	print()
	typing("                    4")
	print()
	typing(f"  outputnya akan berjalan hingga angkanya sama dengan {YELLOW}5{RESET}")
	print()
	input(f"{DARK_GRAY}klik enter untuk kembali.{RESET}")
	main()

def defs():
	delete()
	typing(f"{MAGENTA}\x1B[3mdef\x1B[3m{RESET}(define) adalah fungsi yang menyimpan sejumlah data di dalamnya.")
	print()
	typing(f"di dalam {MAGENTA}\x1B[3mdef\x1B[3m{RESET}, bisa terkandung segala sesuatu yang kamu sudah pelajari.")
	print()
	typing(f"ada 2 cara pemanggilan {MAGENTA}\x1B[3mdef\x1B[3m{RESET}, tergantung kamu mau panggil isinya atau milainya")
	print()
	typing(f"jika mau memanggin nilainya kamu harus memakai yang namanya {MAGENTA}return{RESET}")
	print()
	typing(f"apakah kamu mau tau tentang fungsi {MAGENTA}return{RESET}? y/n")
	print()
	x=input(">")
	if x=='y':
		typing(f"{MAGENTA}return{RESET} adalah fungsi yang mengembalikan sebuah variable dalam {MAGENTA}\x1B[3mdef\x1B[3m{RESET}.")
		print()
		typing(f"untuk contoh penggunaannya nanti di contoh pemanggilan nilai {MAGENTA}\x1B[3mdef\x1B[3m{RESET}")
		print()
		input(f"{DARK_GRAY}klik enter untuk melanjutkan.{RESET}")
		print()
	else:
		print()
	typing(f"1. pemanggilan isi {MAGENTA}\x1B[3mdef\x1B[3m{RESET}")
	print()
	typing(f"   isi {MAGENTA}\x1B[3mdef\x1B[3m{RESET} dapat di panggil dengan cara mengetikkan {BLUE}namadef{RESET}()")
	print()
	typing(f"   contohnya: {MAGENTA}\x1B[3mdef\x1B[3m{RESET} {BRIGHT_BLUE}kalimat{RESET}():")
	print()
	typing(f"                  {BLUE}\x1B[3mprint\x1B[3m{RESET}({BRIGHT_BLUE}'{BRIGHT_GREEN}halo {name}{BRIGHT_BLUE}'{RESET})")
	print()
	typing(f"                  {BLUE}\x1B[3mprint\x1B[3m{RESET}({BRIGHT_BLUE}'{BRIGHT_GREEN}kamu terlihat sangat bagus hari ini{BRIGHT_BLUE}'{RESET})")
	print()
	typing(f"              {BLUE}kalimat{RESET}()")
	print()
	typing(f"   outputnya adalah: halo {name}")
	print()
	typing("                     kamu terlihat sangat bagus hari ini")
	print()
	input(f"{DARK_GRAY}klik enter untuk melanjutkan.{RESET}")
	print()
	typing(f"2. pemanggilan nilai {MAGENTA}\x1B[3mdef\x1B[3m{RESET}")
	print()
	typing(f"   nilai {MAGENTA}\x1B[3mdef\x1B[3m{RESET} dapat di panggil dengan cara mengetikkan {MAGENTA}return{RESET} variabel")
	print()
	typing(f"   contohnya: {MAGENTA}\x1B[3mdef\x1B[3m{RESET} {BRIGHT_BLUE}angka{RESET}():")
	print()
	typing(f"                  x{RED}={YELLOW}16")
	print()
	typing(f"                  {MAGENTA}return{RESET} x")
	print()
	typing(f"                  {BLUE}\x1B[3mprint\x1B[3m{RESET}({BLUE}angka{RESET}())")
	print()
	typing("   outputnya adalah: 16")
	print()
	input(f"{DARK_GRAY}klik enter untuk melanjutkan.{RESET}")
	print()
	typing(f"{MAGENTA}\x1B[3mdef\x1B[3m{RESET} juga bisa digunakan untuk membuat sebuah fungsi ")
	print()
	typing(f"contohnya: {MAGENTA}\x1B[3mdef\x1B[3m{RESET} {BRIGHT_BLUE}kali_4{RESET}({YELLOW}var{RESET}):")
	print()
	typing(f"               hasil{RED}={YELLOW}4{RED}*{RESET}var")
	print()
	typing(f"               {MAGENTA}return{RESET} hasil")
	print()
	typing(f"           {BLUE}\x1B[3mprint\x1B[3m{RESET}({BLUE}kali_4{RESET}({YELLOW}6{RESET}))")
	print()
	typing("outputnya adalah: 24")
	print()
	typing("pusing? saya juga hehe")
	print()
	input(f"{DARK_GRAY}klik enter untuk kembali.{RESET}")
	main()

def listing():
	delete()
	typing(f"nah, tadi {BLUE}\x1B[3mlist\x1B[3m{RESET} sudah ku jelaskan di jenis, jenis tipe data.")
	print()
	typing(f"namun, {BLUE}\x1B[3mlist\x1B[3m{RESET} juga memiliki beberapa fungsi khusus, yaitu:")
	print()
	typing(f"1.{BLUE}append{RESET}")
	print()
	typing(f"2.{BLUE}insert{RESET}")
	print()
	typing(f"3.{MAGENTA}del{RESET}")
	print()
	typing(f"4.{BLUE}remove{RESET}")
	print()
	typing(f"5.{MAGENTA}for{RESET}... {BLUE}\x1B[3menumerate\x1B[3m{RESET}")
	print()
	input(f"{DARK_GRAY}klik enter untuk melanjutkan.{RESET}")
	print()
	typing(f"1. {BLUE}append{RESET}")
	print()
	typing(f"   {BLUE}append{RESET} adalah fungsi untuk menambahkan sebuah variabel ke index terakhir {BLUE}\x1B[3mlist\x1B[3m{RESET}")
	print()
	typing(f"   contohnya: list{RED}={RESET}[{BRIGHT_BLUE}'{BRIGHT_GREEN}{name}{BRIGHT_BLUE}'{GRAY},{BRIGHT_BLUE}'{BRIGHT_GREEN}Ave{BRIGHT_BLUE}'{RESET}]")
	print()
	typing(f"              list.{BLUE}append{RESET}({BRIGHT_BLUE}'{BRIGHT_GREEN}Blake{BRIGHT_BLUE}'{RESET})")
	print()
	typing(f"              {BLUE}\x1B[3mprint\x1B[3m{RESET}(list)")
	print()
	typing(f"   outputnya adalah: ['{name}','Ave','Blake']")
	print()
	input(f"{DARK_GRAY}klik enter untuk melanjutkan.{RESET}")
	print()
	typing(f"2. {BLUE}insert{RESET}")
	print()
	typing(f"   {BLUE}insert{RESET} adalah fungsi yang menambahkan sebuah variable ke dalam tempat {BLUE}\x1B[3mlist\x1B[3m{RESET} yang ditentukan")
	print()
	typing(f"   contohnya: list{RED}={RESET}[{BRIGHT_BLUE}'{BRIGHT_GREEN}{name}{BRIGHT_BLUE}'{GRAY},{BRIGHT_BLUE}'{BRIGHT_GREEN}Blake{BRIGHT_BLUE}'{RESET}]")
	print()
	typing(f"              list.{BLUE}insert{RESET}({YELLOW}1{GRAY},{BRIGHT_BLUE}'{BRIGHT_GREEN}Blake{BRIGHT_BLUE}'{RESET}) {GRAY}#ini menambahkan variabel ke index kedua")
	print()
	typing(f"              {BLUE}\x1B[3mprint\x1B[3m{RESET}(list)")
	print()
	typing(f"   outputnya adalah: ['{name}','Ave','Blake']")
	print()
	input(f"{DARK_GRAY}klik enter untuk melanjutkan.{RESET}")
	print()
	typing(f"3. {MAGENTA}del{RESET}")
	print()
	typing(f"   {MAGENTA}del{RESET} adalah fungsi yang menghapus sebuah variable ke dalam tempat {BLUE}\x1B[3mlist\x1B[3m{RESET} yang ditentukan")
	print()
	typing(f"   contohnya: list{RED}={RESET}[{BRIGHT_BLUE}'{BRIGHT_GREEN}Saya{BRIGHT_BLUE}'{GRAY},{BRIGHT_BLUE}'{BRIGHT_GREEN}Sangat{BRIGHT_BLUE}'{GRAY},{BRIGHT_BLUE}'{BRIGHT_GREEN}Tidak{BRIGHT_BLUE}'{GRAY},{BRIGHT_BLUE}'{BRIGHT_GREEN}Suka{BRIGHT_BLUE}'{GRAY},{BRIGHT_BLUE}'{BRIGHT_GREEN}{name}{BRIGHT_BLUE}'{RESET}]")
	print()
	typing(f"              {MAGENTA}del{RESET} list[{YELLOW}2{RESET}]")
	print()
	typing(f"              {BLUE}\x1B[3mprint\x1B[3m{RESET}(list)")
	print()
	typing(f"   outputnya adalah: ['Saya','Sangat','Suka','{name}']")
	print()
	input(f"{DARK_GRAY}klik enter untuk melanjutkan.{RESET}")
	print()
	typing(f"4. {BLUE}remove{RESET}")
	print()
	typing(f"   {BLUE}remove{RESET} adalah fungsi yang menghapus sebuah variable di dalam {BLUE}\x1B[3mlist\x1B[3m{RESET} berdasarkan nilainya")
	print()
	typing(f"   contohnya: list{RED}={RESET}[{BRIGHT_BLUE}'{BRIGHT_GREEN}Saya{BRIGHT_BLUE}'{GRAY},{BRIGHT_BLUE}'{BRIGHT_GREEN}Sangat{BRIGHT_BLUE}'{GRAY},{BRIGHT_BLUE}'{BRIGHT_GREEN}Tidak{BRIGHT_BLUE}'{GRAY},{BRIGHT_BLUE}'{BRIGHT_GREEN}Suka{BRIGHT_BLUE}'{GRAY},{BRIGHT_BLUE}'{BRIGHT_GREEN}{name}{BRIGHT_BLUE}'{RESET}]")
	print()
	typing(f"              list.{BLUE}remove{RESET}({BRIGHT_BLUE}'{BRIGHT_GREEN}Tidak{BRIGHT_BLUE}'{RESET})")
	print()
	typing(f"              {BLUE}\x1B[3mprint\x1B[3m{RESET}(list)")
	print()
	typing(f"   outputnya adalah: ['Saya','Sangat','Suka','{name}']")
	print()
	input(f"{DARK_GRAY}klik enter untuk melanjutkan.{RESET}")
	print()
	typing(f"5. {MAGENTA}for{RESET}... {BLUE}\x1B[3menumerate\x1B[3m{RESET}")
	print()
	typing(f"   {MAGENTA}for{RESET}... {BLUE}\x1B[3menumerate\x1B[3m{RESET} adalah fungsi untuk mengurutkan {BLUE}\x1B[3mlist\x1B[3m{RESET}")
	print()
	typing(f"   fungsi {MAGENTA}for{RESET}... {BLUE}\x1B[3menumerate\x1B[3m{RESET} membuat 2 variabel baru, 1 untuk angka dan 1 untuk isinya")
	print()
	typing(f"   contohnya: list{RED}={RESET}[{BRIGHT_BLUE}'{BRIGHT_GREEN}{name}{BRIGHT_BLUE}'{GRAY},{BRIGHT_BLUE}'{BRIGHT_GREEN}Baik Hati{BRIGHT_BLUE}'{GRAY},{BRIGHT_BLUE}'{BRIGHT_GREEN}Justin{BRIGHT_BLUE}'{GRAY},{BRIGHT_BLUE}'{RESET}]")
	print()
	print(f"{DARK_GRAY}ini untuk nomor urut (bisa di namakan apa saja) tapi dia mulai dari 0, makanya harus di panggil pakai +1")
	print()
	print(f"                      |     ini adalah variabel yang berisi isi listnya (bisa dinamakan apa saja)")
	print()
	print(f"                      |     |   arti in adalah untuk membuat variabel Nama memiliki isi yang sama dengan listnya  ")
	print()
	print(f"                      |     |   |  enumerate(list) artinya dia mengurutkan listnya(Nama) ")
	print()
	print(f"                      ↓     ↓   ↓  ↓     berpasangan dengan index sampai list nya habis{RESET}")
	print()
	typing(f"              {MAGENTA}for{RESET} Index, Nama {RED}in {BLUE}\x1B[3menumerate\x1B[3m{RESET}(list):")
	print()
	typing(f"                  {BLUE}\x1B[3mprint\x1B[3m{RESET}({MAGENTA}\x1B[3mf\x1B[3m{BRIGHT_BLUE}'{RESET}{sekilas}Index{RED}+{YELLOW}1{RESET}{sekilas1}. {sekilas}Nama{sekilas1}{BRIGHT_BLUE}'{RESET}) #ini dia memanggil nomor urut. isi listnya") 
	print()
	typing(f"   outputnya adalah: 1. {name}")
	print()
	typing("                     2. Baik Hati")
	print()
	typing("                     3. Justin")
	print()
	input(f"{DARK_GRAY}klik enter untuk kembali.{RESET}")
	main()

def imports():
	delete()
	typing(f"seperti namanya, fungsi {MAGENTA}import{RESET} berfungsi untuk meng{MAGENTA}import{RESET} sebuah librari yang berisi fungsi-fungsi yang berbeda")
	print()
	help('modules')
	print()
	print()
	typing("ini adalah module bawaan dari python yang kamu miliki")
	print()
	input(f"{DARK_GRAY}klik enter untuk melanjutkan.{RESET}")
	print()
	typing(f"module tersebut harus dipanggil menggunakan {MAGENTA}import{RESET} jika kamu ingin gunakan")
	print()
	typing(f"{MAGENTA}import{RESET} juga bisa digunakan untuk memanggil fungsi dari module yang kamu import menggunakan {MAGENTA}from{RESET}")
	print()
	typing(f"{MAGENTA}import{RESET} bisa juga diganti namanya menggunakan {MAGENTA}as{RESET}")
	print()
	print()
	typing(f"contohnya: {MAGENTA}import{RESET} math {GRAY}#mengimport modul math")
	print()
	typing(f"           {MAGENTA}from{RESET} math {MAGENTA}import{RESET} sqrt {MAGENTA}as{RESET} akar {GRAY}#mengimport fungsi sqrt dari math dan menamainya akar")
	print()
	typing(f"           {BLUE}\x1B[3mprint\x1B[3m{RESET}({BLUE}\x1B[3makar\x1B[3m{RESET}({YELLOW}9{RESET}))")
	print()
	typing("outputnya adalah: 3.0")
	print()
	input(f"{DARK_GRAY}klik enter untuk kembali.{RESET}")
	main()

def tryex():
	delete()
	typing(f"untuk {MAGENTA}try{RESET},{MAGENTA}except{RESET},{MAGENTA}else{RESET},{MAGENTA}finally{RESET}")
	print()
	typing(f"1.{MAGENTA}try{RESET}")
	print()
	typing(f"  seperti namanya, {MAGENTA}try{RESET} berfungsi untuk mencoba menjalankan sebuah program")
	print()
	input(f"{DARK_GRAY}klik enter untuk melanjutkan.{RESET}")
	print()
	typing(f"2.{MAGENTA}except{RESET}")
	print()
	typing(f"  {MAGENTA}except{RESET} berfungsi untuk menanggulangi kesalahan agar program tidak tertutup langsung")
	print()
	typing(f"  {MAGENTA}except{RESET} hanya akan berjalan ketika ada sebuah error.")
	print()
	typing(f"  {MAGENTA}except{RESET} biasa diketik dengan format: {MAGENTA}except{RESET} {BLUE}\x1B[3mException\x1B[3m {MAGENTA}as{RESET} e:")
	print()
	input(f"{DARK_GRAY}klik enter untuk melanjutkan.{RESET}")
	print()
	typing(f"3.{MAGENTA}else{RESET}")
	print()
	typing(f"  terbalik dengan fungsi {MAGENTA}except{RESET}, fungsi {MAGENTA}else{RESET} hanya dapat berjalan ketika tidak ada error.")
	print()
	input(f"{DARK_GRAY}klik enter untuk melanjutkan.{RESET}")
	print()
	typing(f"4.{MAGENTA}finally{RESET}")
	print()
	typing(f"  fungsi {MAGENTA}finally{RESET} akan selalu berjalan mau ada error ataupun tidak")
	print()
	input(f"{DARK_GRAY}klik enter untuk melanjutkan.{RESET}")
	print()
	typing("contoh penggunaan keempat fungsi tersebut:")
	print()
	typing(f"{MAGENTA}try{RESET}:")
	print()
	typing(f"    angka{RED}={BLUE}int{RESET}({BLUE}input{RESET}({BRIGHT_BLUE}'{BRIGHT_GREEN}masukkan sebuah angka: {BRIGHT_BLUE}'{RESET}))")
	print()
	typing(f"    {BLUE}\x1B[3mprint\x1B[3m{RESET}({MAGENTA}\x1B[3mf\x1B[3m{BRIGHT_BLUE}'{BRIGHT_GREEN}Angka kamu adalah: {RESET}{sekilas}angka{sekilas1}{BRIGHT_BLUE}'{RESET})")
	print()
	typing(f"{MAGENTA}except{RESET} {BLUE}\x1B[3mException\x1B[3m {MAGENTA}as{RESET} e:")
	print()
	typing(f"       {BLUE}\x1B[3mprint\x1B[3m{RESET}({BRIGHT_BLUE}'{BRIGHT_GREEN}Errornya adalah:{BRIGHT_BLUE}'{RESET}{GRAY},{RESET} e)")
	print()
	typing(f"{MAGENTA}else{RESET}:")
	print()
	typing(f"    {BLUE}\x1B[3mprint\x1B[3m{RESET}({BRIGHT_BLUE}'{BRIGHT_GREEN}{name} Yang Baik{BRIGHT_BLUE}'{RESET})")
	print()
	typing(f"{MAGENTA}finally{RESET}:")
	print()
	typing(f"    {BLUE}\x1B[3mprint\x1B[3m{RESET}({BRIGHT_BLUE}'{BRIGHT_GREEN}{name} Yang pintar{BRIGHT_BLUE}'{RESET})")
	print()
	print()
	typing(f"sekarang saya akan coba input yang pertama itu '12' dan yang kedua itu '{name}' ")
	print()
	typing("output untuk input yang pertama adalah: masukkan sebuah angka: 12")
	print()
	typing("                                        Angka kamu adalah: 12")
	print()
	typing(f"                                        {name} Yang Baik")
	print()
	typing(f"                                        {name} Yang pintar")
	print()
	print()
	typing(f"output untuk input yang kedua adalah: masukkan sebuah angka: {name}")
	print()
	typing(f"                                      Errornya adalah: invalid literal for int() with base 10: '{name}'")
	print()
	typing(f"                                      {name} Yang pintar")
	print()
	input(f"{DARK_GRAY}klik enter untuk kembali.{RESET}")
	main()

def globals():
	delete()
	typing(F"{RED}global{RESET} merupakan sebuah tipe data.")
	print()
	typing(F"{RED}global{RESET} berguna untuk sebuah variabel yang kamu ingin ubah isinya di {MAGENTA}\x1B[3mdef\x1B[3m{RESET}.")
	print()
	typing(f"contohnya: umur{RED}={YELLOW}0{RESET}")
	print()
	typing(f"           {MAGENTA}\x1B[3mdef\x1B[3m{RESET} {BRIGHT_BLUE}tambahumur{RESET}():")
	print()
	typing(f"               {RED}global{RESET} umur")
	print()
	typing(f"               umur{RED}+={YELLOW}16{RESET}")
	print()
	typing(f"           {BLUE}tambahumur{RESET}()")
	print()
	typing(f"           {BLUE}\x1B[3mprint\x1B[3m{RESET}({MAGENTA}\x1B[3mf\x1B[3m{BRIGHT_BLUE}'{BRIGHT_GREEN}saya berumur {RESET}{sekilas}umur{sekilas1}{BRIGHT_GREEN} tahun{BRIGHT_BLUE}'{RESET})")
	print()
	typing("outputnya adalah: saya berumur 16 tahun")
	print()
	typing(f"{RED}global{RESET} juga bisa digunakan untuk mengubah sebuah variabel di dalam beberapa {MAGENTA}\x1B[3mdef\x1B[3m{RESET}")
	print()
	typing(f"yang pengting deklarasikan dulu variabel dan {RED}global{RESET} nya")
	print()
	input(f"{DARK_GRAY}klik enter untuk kembali.{RESET}")
	main()
name=input("Siapa Namamu? >")
main()